name: HermesMacOS
options:
  bundleIdPrefix: fr.dubertrand
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    MACOSX_DEPLOYMENT_TARGET: 14.0
targets:
  HermesMacOS:
    type: application
    platform: macOS
    sources:
      - HermesMacOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: fr.dubertrand.HermesMacOS
        PRODUCT_NAME: HermesMacOS
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Laurent Dubertrand"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "HermesMacOS can attach and send selected files to Hermes."
